### ISSUE TITLE
Failed to read property of 'root'.

### ISSUE THREAD

**Issue by Gungo** [FrancescoSaverioZuppichini/DrawIo2Vuejs#1]
My UML design looks like this: https://drive.google.com/file/d/1zcmP_ZzBVvfhH8AZmkZ6FuorrunNFr2A/view?usp=sharing

and running the command in my vue apps directory:

```drawio2vuejs --xml=./XML/AppXML.xml --dist=./src
events.js:167
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'root' of undefined
    at parseString (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/graph2app-drawio-graph-builder/src/DrawIoGraphBuilder.js:49:43)
    at Parser.<anonymous> (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:182:13)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/xml2js/lib/parser.js:5:59)
Emitted 'error' event at:
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/xml2js/lib/parser.js:326:16)
    at Parser.parseString (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/xml2js/lib/parser.js:354:19)
    at fs.readFile (/usr/local/lib/node_modules/graph2app-drawio2vuejs/node_modules/graph2app-drawio-graph-builder/src/DrawIoGraphBuilder.js:47:7)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)```

**Comment by FrancescoSaverioZuppichini** [comment]
Hi Gungo, sorry for the late reply. I am very busy  atm, I will have a look at soon as I can
